Dev
mercihabam/thegym-bem-challenge3-sass pull request #1
Opened 2022-10-11 10:59 UTC by jacob-js

2022-10-11 15:59 UTC, alain-kubwayo requested changes
### Good job on the project
Please check out [this](https://musayann.notion.site/BEM-reviews-highlights-0d16ab192f134555a6f9ecf64a230498), revise your work accordingly, and re-request reviews.

2022-10-12 14:48 UTC, Nkaka23dev commented on index.html
> +                <div class="qualities_desc">Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy.</div>
This is not BEM

2022-10-12 14:48 UTC, Nkaka23dev commented on index.html
> +                <div class="qualities_desc">Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy.</div>
Same here not BEM

2022-10-12 14:48 UTC, Nkaka23dev commented on index.html
> +            </div>
Not BEM

2022-10-12 14:48 UTC, Nkaka23dev commented on index.html
> +    <section class="why-us">
Why-us is not a agood name for a block in BEM, you can name it like work or business

2022-10-12 14:48 UTC, Nkaka23dev commented on index.html
> +    <section class="stats">
stats name is not descriptive, give it a meaningfull name

2022-10-12 14:48 UTC, Nkaka23dev commented on index.html
> +            <button class="stats__trial-btn">Get Free trial</button>
stats__trial-btn same here

2022-10-12 14:48 UTC, Nkaka23dev commented on index.html
> +                        <div class="discover-more__item-desc">Lorem ipsum dolor sit amet, consetetur sadipscing elitr.</div>
discover-more__item-desc, is not descriptive desc is meaningful I suggest you change it to be discover-more__description

2022-10-12 14:48 UTC, Nkaka23dev commented on index.html
> +                        <div class="discover-more__item-name">Project Management</div>
same here.

2022-10-12 14:48 UTC, Nkaka23dev commented on index.html
> +                        <div class="discover-more__item-desc">Lorem ipsum dolor sit amet, consetetur sadipscing elitr.</div>
same here desc should be changed

2022-10-12 14:48 UTC, Nkaka23dev commented on index.html
> +                        <div class="discover-more__item-desc">Lorem ipsum dolor sit amet, consetetur sadipscing elitr.</div>
Here also

2022-10-12 14:48 UTC, Nkaka23dev commented on index.html
> +                <div class="features__desc">Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy.</div>
features__desc should be feature__description.

2022-10-12 14:48 UTC, Nkaka23dev commented on index.html
> +            </div>
here also

2022-10-12 14:48 UTC, Nkaka23dev commented on index.html
> +                <div class="features__desc">Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy.</div>
and here

2022-10-12 14:48 UTC, Nkaka23dev commented on index.html
> +                <div class="clients__msg">Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.</
clients__msg should be clients__message

2022-10-12 14:48 UTC, Nkaka23dev commented on index.html
> +                <div class="clients__msg">Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.</
Same here

2022-10-12 14:48 UTC, Nkaka23dev commented on index.html
> +                <div class="clients__msg">Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.</
And here

2022-10-12 14:48 UTC, Nkaka23dev commented on index.html
> +    <div class="call-to-act">
call to act is not a good name it should atleast be named pricing

2022-10-12 14:48 UTC, Nkaka23dev commented on pricing.html
> +                <div class="pricing__description mt-8">Lorem ipsum dolor sit amet, consetetur sadipscing elitr.</div>
mt-8 should be in css file instead of html

2022-10-13 06:56 UTC, alain-kubwayo requested changes
### Good job
---
Few minor adjustments to make.

2022-10-13 06:56 UTC, alain-kubwayo commented on product.html
> +    </section>
You should use a meaningful name here. `prod`

2022-10-13 06:56 UTC, alain-kubwayo commented on product.html
> +    <section class="p-20 flex justify-between">
Consider adding these classes to the CSS file with`@apply` directive and call a class instead to keep your HTML clean.

2022-10-13 06:56 UTC, alain-kubwayo commented on product.html
> +    <section class="prod-features">
Same naming issue here too.  Adjust `prod-..` name to be more descriptive for this section.

2022-10-13 06:56 UTC, alain-kubwayo commented on product.html
> +        <div class="insights__content relative z-10">
You should add these classes to the CSS file and use a custom class name instead that follow BEM convention to be consistent.

2022-10-13 06:56 UTC, alain-kubwayo commented on product.html
> +        <div class="grid grid-cols-[45%,1fr] items-center gap-20 p-20 relative z-10">
Please move these classes to the CSS file.

2022-10-13 06:56 UTC, alain-kubwayo commented on product.html
> +        <img src="./assets/img/footer-blur-bg.png" alt="" class="view-pricing__blur-bg">
`view-pricing__blur-bg` is kind of confusing. Try maybe `view-pricing__blurred-background` or similar descriptive names.

2022-10-13 10:50 UTC, alain-kubwayo requested changes
### Good job working on the requested changes. 
---
Address the following minor issue.

2022-10-13 10:50 UTC, alain-kubwayo commented on product.html
> +    <section class="insights">grid grid-cols-[45%,1fr] items-center gap-20 p-20 relative z-10
These classes shouldn't be here. Consider moving them to the external CSS file or simply delete them if you're not using them and already have `insights` block.

2022-10-13 11:10 UTC, Nkaka23dev reviewed
Great job! only a few bugs to iron it up.

2022-10-13 11:10 UTC, Nkaka23dev commented on style.css
> +    .s-hero__gradient, .hero__gradient, .product-hero__gradient{
use tailwind class instead of custom csss

2022-10-13 11:10 UTC, Nkaka23dev commented on style.css
> +    .c-gradient-title, .qualities__title, .work__title, .discover-more__title, .insights__gradient-title{
use tailwind class instead of css

2022-10-13 11:10 UTC, Nkaka23dev commented on style.css
> +    .product-features::before{
use tailwind class instead of custom css

2022-10-20 12:45 UTC, Nkaka23dev approved these changes

2022-10-20 14:27 UTC, alain-kubwayo approved these changes
Good job!

2022-10-25 12:47 UTC, karemarsy reviewed
you should also read this notion https://musayann.notion.site/BEM-reviews-highlights-0d16ab192f134555a6f9ecf64a230498

2022-10-25 12:47 UTC, karemarsy commented on product.html
> +                <img src="./assets/icons/product/feat1.svg" alt="" class="features__icon">
`features__icon` is positioned outside the Block (features).

2022-10-26 08:32 UTC, jacob-js commented
![](https://github.trello.services/images/mini-trello-icon.png) [Merci Jacob, BEM exercise 3](https://trello.com/c/vOUWhlf5/46-merci-jacob-bem-exercise-3)

2022-11-01 15:26 UTC, karemarsy approved these changes

2022-11-01 15:27 UTC, merged